"""empty message

Revision ID: 54c27ca9e26c
Revises: 
Create Date: 2019-09-11 19:12:04.668010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c27ca9e26c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('ballot_slot', sa.DateTime(), nullable=True),
    sa.Column('ballot_position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_ballot_position'), 'user', ['ballot_position'], unique=False)
    op.create_index(op.f('ix_user_ballot_slot'), 'user', ['ballot_slot'], unique=False)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_surname'), 'user', ['surname'], unique=False)
    op.create_index(op.f('ix_user_year'), 'user', ['year'], unique=False)
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crsid', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crsid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('taken_by', sa.String(), nullable=True),
    sa.Column('weekly_rent', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.ForeignKeyConstraint(['taken_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_floor'), 'room', ['floor'], unique=False)
    op.create_index(op.f('ix_room_taken_by'), 'room', ['taken_by'], unique=False)
    op.create_index(op.f('ix_room_type'), 'room', ['type'], unique=False)
    op.create_index(op.f('ix_room_weekly_rent'), 'room', ['weekly_rent'], unique=False)
    op.create_table('ballot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('crsid', sa.String(), nullable=True),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crsid'], ['user.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ballot_timestamp'), 'ballot', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ballot_timestamp'), table_name='ballot')
    op.drop_table('ballot')
    op.drop_index(op.f('ix_room_weekly_rent'), table_name='room')
    op.drop_index(op.f('ix_room_type'), table_name='room')
    op.drop_index(op.f('ix_room_taken_by'), table_name='room')
    op.drop_index(op.f('ix_room_floor'), table_name='room')
    op.drop_table('room')
    op.drop_table('admins')
    op.drop_index(op.f('ix_user_year'), table_name='user')
    op.drop_index(op.f('ix_user_surname'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_ballot_slot'), table_name='user')
    op.drop_index(op.f('ix_user_ballot_position'), table_name='user')
    op.drop_table('user')
    op.drop_table('site')
    # ### end Alembic commands ###
