"""empty message

Revision ID: 7542373e89f2
Revises: 54c27ca9e26c
Create Date: 2019-09-11 19:46:58.193638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7542373e89f2'
down_revision = '54c27ca9e26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site')
    op.add_column('room', sa.Column('friendly_name', sa.String(), nullable=True))
    op.add_column('room', sa.Column('site', sa.String(), nullable=True))
    op.create_index(op.f('ix_room_friendly_name'), 'room', ['friendly_name'], unique=False)
    op.create_index(op.f('ix_room_site'), 'room', ['site'], unique=False)
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_column('room', 'site_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('site_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'room', 'site', ['site_id'], ['id'])
    op.drop_index(op.f('ix_room_site'), table_name='room')
    op.drop_index(op.f('ix_room_friendly_name'), table_name='room')
    op.drop_column('room', 'site')
    op.drop_column('room', 'friendly_name')
    op.create_table('site',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('site', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
